version: '3.9'

services:
  # node:
  #   container_name: nestjs
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./:/app
  #   environment:
  #     - NODE_ENV= 'development'
  #     - NODE_PORT= 3000
  #     - MONGO_URL= 'mongodb://mongo/example'
  #   depends_on:
  #     - mongo
  #   networks:
  #     - common  

  db:
    image: postgres:14.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - common
  


networks:
  common: